/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_uah_pmureader_NativeLib */

#ifndef _Included_com_uah_pmureader_NativeLib
#define _Included_com_uah_pmureader_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_uah_pmureader_NativeLib
 * Method:    initPmuGathering
 * Signature: (IIIIIII)V
 */
JNIEXPORT jint JNICALL Java_com_uah_pmureader_NativeLib_initPmuGathering
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jstring, jstring);

/*
 * Class:     com_uah_pmureader_NativeLib
 * Method:    startSampleGathering
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uah_pmureader_NativeLib_startSampleGathering
  (JNIEnv *, jobject);

/*
 * Class:     com_uah_pmureader_NativeLib
 * Method:    stopSampleGathering
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_uah_pmureader_NativeLib_stopSampleGathering
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
